pipeline {
    agent any
    stages {
        stage('Initialising variables') {
            steps {
                script{
                    PROCESS_OUTPUT_PATH = "${WORKSPACE}\\Process\\Output\\${BUILD_NUMBER}"
                    ASSETS_FILE_PATH = "${WORKSPACE}\\assets.csv"
                }
            }
        }
        stage('Checkout code') {
            steps {
                git branch: 'main',
                credentialsId: 'SebastianBalanLiveCredential',
                url: 'https://github.com/SebastianBalan/Pipeline'
            }
        }
        stage('Pack the project') {
            steps {
                 echo 'UiPathPack'
                 echo PROCESS_OUTPUT_PATH
                 UiPathPack (
                     outputPath: PROCESS_OUTPUT_PATH,
                     outputType: 'Process',
                     projectJsonPath: "${WORKSPACE}",
                     runWorkflowAnalysis: false,
                     traceLevel: 'None',
                     version: AutoVersion()
                 )
            }
        }
        stage('Deploy Project') {
            steps {
                 echo 'UiPathDeploy'
                 UiPathDeploy (
                 createProcess: true,
                 credentials: Token(accountName: 'aitraining', credentialsId: 'userkeyOrch'),
                 entryPointPaths: 'Main.xaml',
                 environments: '',
                 folderName: 'sebi',
                 orchestratorAddress: 'https://cloud.uipath.com/aitraining',
                 orchestratorTenant: 'UiPathDefault',
                 packagePath: PROCESS_OUTPUT_PATH,
                 traceLevel: 'None'
                )
            }
        }
        stage('Deploy Assets') {
            steps {
                 echo 'UiPathAssets'
                 UiPathAssets (
                 assetsAction: DeployAssets(),
                 credentials: Token(accountName: 'aitraining', credentialsId: 'userkeyOrch'),
                 filePath: ASSETS_FILE_PATH,
                 folderName: 'sebi',
                 orchestratorAddress: 'https://cloud.uipath.com/aitraining',
                 orchestratorTenant: 'UiPathDefault',
                 traceLevel: 'None'
                 )
            }
        }
    }
}